"""initial migration

Revision ID: f0ff82e942dc
Revises: 
Create Date: 2026-03-08 00:05:36.542949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ff82e942dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledgebaseitem_entity_id'), table_name='knowledgebaseitem')
    op.drop_index(op.f('ix_knowledgebaseitem_graph_id'), table_name='knowledgebaseitem')
    op.drop_index(op.f('ix_knowledgebaseitem_tenant_id'), table_name='knowledgebaseitem')
    op.drop_table('knowledgebaseitem')
    op.alter_column('client', 'sso_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_client_sso_domain'), 'client', ['sso_domain'], unique=False)
    op.drop_constraint(op.f('edge_from_node_id_fkey'), 'edge', type_='foreignkey')
    op.drop_constraint(op.f('edge_edge_type_id_fkey'), 'edge', type_='foreignkey')
    op.drop_constraint(op.f('edge_graph_id_fkey'), 'edge', type_='foreignkey')
    op.drop_constraint(op.f('edge_to_node_id_fkey'), 'edge', type_='foreignkey')
    op.drop_constraint(op.f('edge_client_id_fkey'), 'edge', type_='foreignkey')
    op.create_foreign_key(None, 'edge', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'node', ['from_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'edge_type', ['edge_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'graph', ['graph_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge', 'node', ['to_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('edge_type_graph_id_fkey'), 'edge_type', type_='foreignkey')
    op.drop_constraint(op.f('edge_type_client_id_fkey'), 'edge_type', type_='foreignkey')
    op.create_foreign_key(None, 'edge_type', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'edge_type', 'graph', ['graph_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('graph_client_id_fkey'), 'graph', type_='foreignkey')
    op.create_foreign_key(None, 'graph', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('node_client_id_fkey'), 'node', type_='foreignkey')
    op.drop_constraint(op.f('node_node_type_id_fkey'), 'node', type_='foreignkey')
    op.drop_constraint(op.f('node_graph_id_fkey'), 'node', type_='foreignkey')
    op.create_foreign_key(None, 'node', 'graph', ['graph_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'node', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'node', 'node_type', ['node_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('node_type_graph_id_fkey'), 'node_type', type_='foreignkey')
    op.drop_constraint(op.f('node_type_client_id_fkey'), 'node_type', type_='foreignkey')
    op.create_foreign_key(None, 'node_type', 'graph', ['graph_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'node_type', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('op_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('op_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('op_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('op_user_email_key'), 'op_user', type_='unique')
    op.create_index(op.f('ix_op_user_email'), 'op_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_op_user_email'), table_name='op_user')
    op.create_unique_constraint(op.f('op_user_email_key'), 'op_user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('op_user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('op_user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('op_user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'node_type', type_='foreignkey')
    op.drop_constraint(None, 'node_type', type_='foreignkey')
    op.create_foreign_key(op.f('node_type_client_id_fkey'), 'node_type', 'client', ['client_id'], ['id'])
    op.create_foreign_key(op.f('node_type_graph_id_fkey'), 'node_type', 'graph', ['graph_id'], ['id'])
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.create_foreign_key(op.f('node_graph_id_fkey'), 'node', 'graph', ['graph_id'], ['id'])
    op.create_foreign_key(op.f('node_node_type_id_fkey'), 'node', 'node_type', ['node_type_id'], ['id'])
    op.create_foreign_key(op.f('node_client_id_fkey'), 'node', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'graph', type_='foreignkey')
    op.create_foreign_key(op.f('graph_client_id_fkey'), 'graph', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'edge_type', type_='foreignkey')
    op.drop_constraint(None, 'edge_type', type_='foreignkey')
    op.create_foreign_key(op.f('edge_type_client_id_fkey'), 'edge_type', 'client', ['client_id'], ['id'])
    op.create_foreign_key(op.f('edge_type_graph_id_fkey'), 'edge_type', 'graph', ['graph_id'], ['id'])
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.drop_constraint(None, 'edge', type_='foreignkey')
    op.create_foreign_key(op.f('edge_client_id_fkey'), 'edge', 'client', ['client_id'], ['id'])
    op.create_foreign_key(op.f('edge_to_node_id_fkey'), 'edge', 'node', ['to_node_id'], ['id'])
    op.create_foreign_key(op.f('edge_graph_id_fkey'), 'edge', 'graph', ['graph_id'], ['id'])
    op.create_foreign_key(op.f('edge_edge_type_id_fkey'), 'edge', 'edge_type', ['edge_type_id'], ['id'])
    op.create_foreign_key(op.f('edge_from_node_id_fkey'), 'edge', 'node', ['from_node_id'], ['id'])
    op.drop_index(op.f('ix_client_sso_domain'), table_name='client')
    op.alter_column('client', 'sso_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('knowledgebaseitem',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('graph_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledgebaseitem_pkey'))
    )
    op.create_index(op.f('ix_knowledgebaseitem_tenant_id'), 'knowledgebaseitem', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_knowledgebaseitem_graph_id'), 'knowledgebaseitem', ['graph_id'], unique=False)
    op.create_index(op.f('ix_knowledgebaseitem_entity_id'), 'knowledgebaseitem', ['entity_id'], unique=False)
    # ### end Alembic commands ###
