import asyncio
import os
import sys
from uuid import UUID
from dotenv import load_dotenv

# Ensure we're running from the project root logically if run from apps/api
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
load_dotenv(".env")

from apps.api.database import get_session
from apps.api.models import Client, Graph, ConnectedRepository
from apps.api.ingestors.github.pipeline import GitHubIngestionPipeline

async def run_smoke_test():
    print("🚀 Starting Opscribe GitHub Ingestion Smoke Test")
    print("-------------------------------------------------")
    
    # We will test the raw pipeline against a small public repo
    test_repo_url = "https://github.com/tiangolo/fastapi"
    test_branch = "master" # fastapi uses master
    
    # 1. Fetch the default dev client generated by API on first load
    session_generator = get_session()
    session = next(session_generator)
    
    dev_client_id = UUID("00000000-0000-0000-0000-000000000000")
    client = session.get(Client, dev_client_id)
    
    if not client:
        print("🔧 Dev client not found in DB. Auto-creating...")
        client = Client(
            id=dev_client_id,
            name="Dev User",
            metadata_={"role": "admin", "temporary_auth": True},
        )
        session.add(client)
        session.commit()
        session.refresh(client)
        
    print(f"✅ Found Dev Client: {client.id}")
    
    # 2. Setup the pipeline
    # Since we don't have a GitHub App Private Key yet, we will bypass the token by passing no target_repo
    # This proves the local cloning, walking, parsing, and MinIO S3 export all work end-to-end.
    print(f"📦 Simulating Ingestion for {test_repo_url} (depth=1)")
    pipeline = GitHubIngestionPipeline(
        repo_url=test_repo_url,
        branch=test_branch,
        access_token="" # Bypasses PyJWT token generation so we can test public repo clone
    )
    
    # 3. Run Pipeline
    try:
        report = await pipeline.run()
        print("\n✅ Pipeline Completed Successfully!")
        print(f"   Nodes Found: {len(report.nodes)}")
        print(f"   Edges Found: {len(report.edges)}")
        print(f"   Files Parsed: {len(report.metadata.get('files_parsed', []))} (or via raw lists)")
        
        # 4. Verify graph was created in DB
        graphs = session.query(Graph).filter(Graph.client_id == client.id).all()
        print(f"\n📊 Total Infrastructure Designs in DB: {len(graphs)}")
        for g in graphs:
            print(f"   - {g.name} (Nodes: {len(g.nodes)}, Edges: {len(g.edges)})")

    except Exception as e:
        print(f"\n❌ Pipeline failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(run_smoke_test())
